### ISSUE TITLE
Feature: Implement ESLint Todo Formatter

### ISSUE THREAD

**Issue by renatoi** [scalvert/eslint-formatter-todo#2]
Initial implementation for the ESLint Todo formatter based on the initial [spec](https://github.com/ember-template-lint/ember-template-lint-todo-utils/blob/master/docs/spec.md) that introduces the capability of having "Todo" items in ESLint.

From the **Motivation** section in that spec:

> Linting is a fundamental tool to help ensure the quality of a codebase. Ensuring there are as few linting errors as possible (ideally 0), is a useful measure of a baseline of code hygiene.
> 
> It's common to leverage linting not just for syntax adherence, but also to direct developers to employ standardized patterns. As such, it's a fairly routine activity to introduce new lint rules into a codebase. This introduction, while necessary, can cause unintended friction, such as
>
> - new lint errors being introduced where they previously didn't exist
> - causing unintended delays to shipping new fixes and features
> - an "all or nothing" approach, where new rules require fixing before rollout.
>
> Having the ability to identify violations as todo would allow for this incremental roll out, while providing tools that will allow maintainers to view the full list of todo violations. Todo violations can include a createdDate, allowing thresholds of time to trigger due date violations. This can assist in prioritizing lint rule violation fixes, and can ensure the todo list doesn't remain stagnant.

## Changes

- [ ] Leverage `@ember-template-lint/todo-utils` to parse and generate `.lint-todo` dir
- [ ] Implementation must change severity of results from `2` (error) to `-1` (todo).
- [ ] Results array must be mutated instead of copied (ESLint may produce the wrong exit code if done otherwise).
- [ ] Workflows spec below is followed with the options to `INCLUDE_TODO`, and `UPDATE_TODO`.
- [ ] Ensure adequate test coverage of expected workflows

## Workflows

- when using eslint with the todo formatter with no linting errors

```
 # behaves as normal - no todo functionality
eslint . --format eslint-formatter-todo
```

- when linting failure exists (severity 2) that has a current todo item, switch linting failure's severity to not trigger a failure
  - todo items should not be included in default output
  - todo item counts should be included in counts output

```
 ✖ 8 problems (5 errors, 3 warnings, 2 todo)
```

  - if no problems, no output (as normal)
  - if no problems but environment variable `INCLUDE_TODO=1` is set, output todo count

```
 ✓ 0 problems (0 errors, 0 warnings, 2 todo)
```

  - todo items should be included with output if running with the `INCLUDE_TODO=1` environment variable.

```
INCLUDE_TODO=1 eslint . --format eslint-formatter-todo
```

- when opting in to todo functionality:

```
 # add new todo items for new errors
 # remove todo items for errors that are no longer present
 # existing errors that have todo items should not be modified

UPDATE_TODO=1 eslint . --format eslint-formatter-todo

 # or 

UPDATE_TODO=1 eslint lib/my-inrepo-addon --format eslint-formatter-todo
```

- when you have fixed a todo item, to update todo list:

```
UPDATE_TODO=1 eslint . --format eslint-formatter-todo
```

- when you have deleted a linted file (foo.js), todo files associated with that file become orphaned. You need to run with `UPDATE_TODO=1` to cleanup todo files for that file:

```
UPDATE_TODO=1 eslint . --format eslint-formatter-todo
```

- if using `--fix` to automatically fix errors and warnings, the`UPDATE_TODO=1` must be explicitly called again to clean up the todo list.

```
# this also updates the todo list
eslint . --format eslint-formatter-todo --fix
```

**Comment by scalvert** [comment]
Great start on speccing this out, @renatoi. 

I'm not sure we need `FIX_TODO`, as we can just leverage the `--fix` option to trigger updating any todos after the fixers have all run. This will mean the workflow for fixing will also update todos.

Thoughts?

**Comment by renatoi** [comment]
Yes, that makes sense. I updated it.
